-- ============================================================
-- CALLE TUNING - BASE DE DATOS DESDE CERO
--Nombre del base de datos: calle_tuning_db


-- 1. Roles
CREATE TABLE public.rol (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE
);

-- 2. Usuarios
CREATE TABLE public.usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apellido VARCHAR(100) NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    nombre VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    username VARCHAR(50) NOT NULL UNIQUE,
    rol_id BIGINT NOT NULL,
    CONSTRAINT fk_usuario_rol FOREIGN KEY (rol_id)
        REFERENCES public.rol(id)
);

-- 3. Categorías
CREATE TABLE public.categoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(255),
    nombre VARCHAR(100) NOT NULL UNIQUE
);

-- 4. Marcas
CREATE TABLE public.marca (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE
);

-- 5. Proveedores
CREATE TABLE public.proveedor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    direccion VARCHAR(255),
    email VARCHAR(100),
    nombre VARCHAR(150) NOT NULL,
    telefono VARCHAR(20)
);

-- 6. Clientes
CREATE TABLE public.cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apellido VARCHAR(100) NOT NULL,
    documento VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(100),
    nombre VARCHAR(100) NOT NULL,
    telefono VARCHAR(20)
);

-- 7. Productos
CREATE TABLE public.producto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR(255),
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    nombre VARCHAR(150) NOT NULL,
    precio NUMERIC(10,2) NOT NULL CHECK (precio >= 0),
    stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
    stock_minimo INTEGER NOT NULL DEFAULT 0 CHECK (stock_minimo >= 0),
    categoria_id BIGINT NOT NULL,
    marca_id BIGINT NOT NULL,
    proveedor_id BIGINT NOT NULL,
    CONSTRAINT fk_producto_categoria FOREIGN KEY (categoria_id)
        REFERENCES public.categoria(id),
    CONSTRAINT fk_producto_marca FOREIGN KEY (marca_id)
        REFERENCES public.marca(id),
    CONSTRAINT fk_producto_proveedor FOREIGN KEY (proveedor_id)
        REFERENCES public.proveedor(id)
);

-- 8. Ventas
CREATE TABLE public.venta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (total >= 0),
    cliente_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    CONSTRAINT fk_venta_cliente FOREIGN KEY (cliente_id)
        REFERENCES public.cliente(id),
    CONSTRAINT fk_venta_usuario FOREIGN KEY (usuario_id)
        REFERENCES public.usuario(id)
);

-- 9. Detalle de ventas
CREATE TABLE public.detalle_venta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    precio_unitario NUMERIC(10,2) NOT NULL CHECK (precio_unitario >= 0),
    subtotal NUMERIC(10,2) NOT NULL CHECK (subtotal >= 0),
    producto_id BIGINT NOT NULL,
    venta_id BIGINT NOT NULL,
    CONSTRAINT fk_detalle_producto FOREIGN KEY (producto_id)
        REFERENCES public.producto(id),
    CONSTRAINT fk_detalle_venta FOREIGN KEY (venta_id)
        REFERENCES public.venta(id)
);

-- 10. Movimientos de inventario
CREATE TABLE public.movimiento_inventario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad INTEGER NOT NULL CHECK (cantidad > 0),
    fecha TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    motivo VARCHAR(255),
    tipo_movimiento VARCHAR(20) NOT NULL
        CHECK (tipo_movimiento IN ('ENTRADA', 'SALIDA', 'AJUSTE')),
    producto_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    CONSTRAINT fk_movimiento_producto FOREIGN KEY (producto_id)
        REFERENCES public.producto(id),
    CONSTRAINT fk_movimiento_usuario FOREIGN KEY (usuario_id)
        REFERENCES public.usuario(id)
);

-- ============================================================
-- DATOS INICIALES DE PRUEBA
-- ============================================================

INSERT INTO public.rol (id, nombre) VALUES
    (1, 'Administrador'),
    (2, 'INSTALADOR'),
    (3, 'ELECTRICISTA');

INSERT INTO public.usuario
    (id, apellido, estado, nombre, password, username, rol_id)
VALUES
    (1, 'Berocal Huaripaucar', TRUE, 'Neky', '123456', 'Nekys', 1);

INSERT INTO public.categoria (id, descripcion, nombre) VALUES
    (1, 'Instalación de vinil, wrapping, calcomanías, LED y audio.', 'Personalización'),
    (2, 'Instalación de PPF, sliders de horquilla y chasis.', 'Protección'),
    (3, 'Cascos certificados y accesorios para motociclistas.', 'Cascos y accesorios');

INSERT INTO public.marca (id, nombre) VALUES
    (3, '3M'),
    (4, 'LEOS PARTS'),
    (5, 'LS2');

INSERT INTO public.proveedor (id, direccion, email, nombre, telefono) VALUES
    (1, 'Dirección por registrar', 'cascos_ls2@example.com', 'Cascos LS2', '985214854'),
    (2, 'Dirección por registrar', 'vinilos_3m@example.com', 'Vinil 3M', '963258741'),
    (3, 'Dirección por registrar', 'ppf@example.com', 'Wrapping PPF', '98523654'),
    (4, 'Dirección por registrar', 'leo_parts@example.com', 'LEO Parts Perú', '987654321');

INSERT INTO public.cliente
    (id, apellido, documento, email, nombre, telefono)
VALUES
    (1, 'Huamán', '71339988', 'cliente@example.com', 'Carlos', '900169852');

INSERT INTO public.producto
    (id, descripcion, estado, nombre, precio, stock, stock_minimo,
     categoria_id, marca_id, proveedor_id)
VALUES
    (1, 'Vinil para personalización de motocicletas', TRUE,
     'Vinil para Motocicleta', 180.00, 9, 2, 1, 3, 2),
    (2, 'Película protectora para superficies de motocicleta', TRUE,
     'PPF', 350.00, 20, 2, 2, 3, 3),
    (3, 'Casco certificado para motociclista', TRUE,
     'Casco Homologado', 420.00, 8, 2, 3, 5, 1);

INSERT INTO public.venta (id, fecha, total, cliente_id, usuario_id)
VALUES (1, TIMESTAMP '2026-09-27 10:00:00', 350.00, 1, 1);

INSERT INTO public.detalle_venta
    (id, cantidad, precio_unitario, subtotal, producto_id, venta_id)
VALUES (1, 1, 350.00, 350.00, 2, 1);

INSERT INTO public.movimiento_inventario
    (id, cantidad, fecha, motivo, tipo_movimiento, producto_id, usuario_id)
VALUES
    (1, 10, TIMESTAMP '2026-09-27 09:00:00',
     'Ingreso inicial de productos', 'ENTRADA', 1, 1);

-- Sincronizar los identificadores automáticos después de insertar IDs manuales.
SELECT setval(pg_get_serial_sequence('public.rol', 'id'),
              (SELECT MAX(id) FROM public.rol));
SELECT setval(pg_get_serial_sequence('public.usuario', 'id'),
              (SELECT MAX(id) FROM public.usuario));
SELECT setval(pg_get_serial_sequence('public.categoria', 'id'),
              (SELECT MAX(id) FROM public.categoria));
SELECT setval(pg_get_serial_sequence('public.marca', 'id'),
              (SELECT MAX(id) FROM public.marca));
SELECT setval(pg_get_serial_sequence('public.proveedor', 'id'),
              (SELECT MAX(id) FROM public.proveedor));
SELECT setval(pg_get_serial_sequence('public.cliente', 'id'),
              (SELECT MAX(id) FROM public.cliente));
SELECT setval(pg_get_serial_sequence('public.producto', 'id'),
              (SELECT MAX(id) FROM public.producto));
SELECT setval(pg_get_serial_sequence('public.venta', 'id'),
              (SELECT MAX(id) FROM public.venta));
SELECT setval(pg_get_serial_sequence('public.detalle_venta', 'id'),
              (SELECT MAX(id) FROM public.detalle_venta));
SELECT setval(pg_get_serial_sequence('public.movimiento_inventario', 'id'),
              (SELECT MAX(id) FROM public.movimiento_inventario));

-- Verificación final: muestra las tablas de la aplicación.
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_type = 'BASE TABLE'
  AND table_name IN (
      'rol', 'usuario', 'categoria', 'marca', 'proveedor',
      'cliente', 'producto', 'venta', 'detalle_venta',
      'movimiento_inventario'
  )
ORDER BY table_name;
