--
-- PostgreSQL database dump
--

\restrict xd0tBJrpOdnPFMGkBa2qGMim4ubActLYxBqkbap8veYHGhbaxDAyZlZ8RPzepCs

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.4

-- Started on 2026-09-27 19:55:48

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16877)
-- Name: categoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categoria (
    id bigint NOT NULL,
    descripcion character varying(255),
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.categoria OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16876)
-- Name: categoria_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16885)
-- Name: cliente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cliente (
    id bigint NOT NULL,
    apellido character varying(100) NOT NULL,
    documento character varying(20) NOT NULL,
    email character varying(100),
    nombre character varying(100) NOT NULL,
    telefono character varying(20)
);


ALTER TABLE public.cliente OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16884)
-- Name: cliente_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cliente ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cliente_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16895)
-- Name: detalle_venta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.detalle_venta (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    precio_unitario numeric(10,2) NOT NULL,
    subtotal numeric(10,2) NOT NULL,
    producto_id bigint NOT NULL,
    venta_id bigint NOT NULL
);


ALTER TABLE public.detalle_venta OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16894)
-- Name: detalle_venta_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.detalle_venta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.detalle_venta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16907)
-- Name: marca; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.marca (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.marca OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16906)
-- Name: marca_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.marca ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marca_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16915)
-- Name: movimiento_inventario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.movimiento_inventario (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    fecha timestamp(6) without time zone NOT NULL,
    motivo character varying(255),
    tipo_movimiento character varying(20) NOT NULL,
    producto_id bigint NOT NULL,
    usuario_id bigint NOT NULL
);


ALTER TABLE public.movimiento_inventario OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16914)
-- Name: movimiento_inventario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.movimiento_inventario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimiento_inventario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16927)
-- Name: producto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.producto (
    id bigint NOT NULL,
    descripcion character varying(255),
    estado boolean NOT NULL,
    nombre character varying(150) NOT NULL,
    precio numeric(10,2) NOT NULL,
    stock integer NOT NULL,
    stock_minimo integer NOT NULL,
    categoria_id bigint NOT NULL,
    marca_id bigint NOT NULL,
    proveedor_id bigint NOT NULL
);


ALTER TABLE public.producto OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16926)
-- Name: producto_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.producto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16942)
-- Name: proveedor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.proveedor (
    id bigint NOT NULL,
    direccion character varying(255),
    email character varying(100),
    nombre character varying(150) NOT NULL,
    telefono character varying(20)
);


ALTER TABLE public.proveedor OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16941)
-- Name: proveedor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.proveedor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proveedor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 16952)
-- Name: rol; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rol (
    id bigint NOT NULL,
    nombre character varying(50) NOT NULL
);


ALTER TABLE public.rol OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16951)
-- Name: rol_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rol ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 16960)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id bigint NOT NULL,
    apellido character varying(100) NOT NULL,
    estado boolean NOT NULL,
    nombre character varying(100) NOT NULL,
    password character varying(100) NOT NULL,
    username character varying(50) NOT NULL,
    rol_id bigint NOT NULL
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 16959)
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 16973)
-- Name: venta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.venta (
    id bigint NOT NULL,
    fecha timestamp(6) without time zone NOT NULL,
    total numeric(10,2) NOT NULL,
    cliente_id bigint NOT NULL,
    usuario_id bigint NOT NULL
);


ALTER TABLE public.venta OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 16972)
-- Name: venta_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.venta ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.venta_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5089 (class 0 OID 16877)
-- Dependencies: 220
-- Data for Name: categoria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categoria (id, descripcion, nombre) FROM stdin;
1	Instalación de vinil, wrapping, calcomanías, LED y audio.	Personalización
2	Instalación de PPF, sliders de horquilla y chasis.	Protección
3	cascos para los moteros\n\n	CASCOS CERTIFICADOS
\.


--
-- TOC entry 5091 (class 0 OID 16885)
-- Dependencies: 222
-- Data for Name: cliente; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cliente (id, apellido, documento, email, nombre, telefono) FROM stdin;
1	Huáman	71339988	carlos1_arr@gmail.com	Carlos	900169852
\.


--
-- TOC entry 5093 (class 0 OID 16895)
-- Dependencies: 224
-- Data for Name: detalle_venta; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.detalle_venta (id, cantidad, precio_unitario, subtotal, producto_id, venta_id) FROM stdin;
1	1	350.00	350.00	1	1
\.


--
-- TOC entry 5095 (class 0 OID 16907)
-- Dependencies: 226
-- Data for Name: marca; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.marca (id, nombre) FROM stdin;
3	3M
4	LEOS PARTS
5	LS2
\.


--
-- TOC entry 5097 (class 0 OID 16915)
-- Dependencies: 228
-- Data for Name: movimiento_inventario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.movimiento_inventario (id, cantidad, fecha, motivo, tipo_movimiento, producto_id, usuario_id) FROM stdin;
1	10	2026-09-27 09:00:00	Ingreso de productos	ENTRADA	1	1
\.


--
-- TOC entry 5099 (class 0 OID 16927)
-- Dependencies: 230
-- Data for Name: producto; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.producto (id, descripcion, estado, nombre, precio, stock, stock_minimo, categoria_id, marca_id, proveedor_id) FROM stdin;
1	Vinil automotriz para personalización	t	Vinil para Motocicleta	180.00	9	2	1	3	2
2	Instalacion de pelicula protectora automotriz	t	PPF	350.00	20	2	2	3	3
3	Casco certificado para motociclista	t	Casco Homologado	420.00	8	2	3	5	1
\.


--
-- TOC entry 5101 (class 0 OID 16942)
-- Dependencies: 232
-- Data for Name: proveedor; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.proveedor (id, direccion, email, nombre, telefono) FROM stdin;
1	Av. Canadá 1250, Lima	leo_parts_peru@motoparts.com	LEO Parts Perú	987654321
2	Av. Santa Anita #453	Vinilos_3m_peru@gmail.colm	Vinil 3M	963258741
3	Miraflores 	ppf_waraping_12@gmail.com	Wraping PPF	98523654
4	Av. Comas #125	Cascos_ls2@gmail.com	Cascos LS2	985214854
\.


--
-- TOC entry 5103 (class 0 OID 16952)
-- Dependencies: 234
-- Data for Name: rol; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rol (id, nombre) FROM stdin;
1	Administrador
2	INSTALADOR
3	ELECTRICISTA
\.


--
-- TOC entry 5105 (class 0 OID 16960)
-- Dependencies: 236
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario (id, apellido, estado, nombre, password, username, rol_id) FROM stdin;
1	Berocal Huaripaucar	t	Neky 	123456	Nekys	1
\.


--
-- TOC entry 5107 (class 0 OID 16973)
-- Dependencies: 238
-- Data for Name: venta; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.venta (id, fecha, total, cliente_id, usuario_id) FROM stdin;
1	2026-09-27 10:00:00	350.00	1	1
\.


--
-- TOC entry 5113 (class 0 OID 0)
-- Dependencies: 219
-- Name: categoria_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categoria_id_seq', 3, true);


--
-- TOC entry 5114 (class 0 OID 0)
-- Dependencies: 221
-- Name: cliente_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cliente_id_seq', 1, true);


--
-- TOC entry 5115 (class 0 OID 0)
-- Dependencies: 223
-- Name: detalle_venta_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.detalle_venta_id_seq', 1, true);


--
-- TOC entry 5116 (class 0 OID 0)
-- Dependencies: 225
-- Name: marca_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.marca_id_seq', 5, true);


--
-- TOC entry 5117 (class 0 OID 0)
-- Dependencies: 227
-- Name: movimiento_inventario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.movimiento_inventario_id_seq', 1, true);


--
-- TOC entry 5118 (class 0 OID 0)
-- Dependencies: 229
-- Name: producto_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.producto_id_seq', 3, true);


--
-- TOC entry 5119 (class 0 OID 0)
-- Dependencies: 231
-- Name: proveedor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.proveedor_id_seq', 4, true);


--
-- TOC entry 5120 (class 0 OID 0)
-- Dependencies: 233
-- Name: rol_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rol_id_seq', 3, true);


--
-- TOC entry 5121 (class 0 OID 0)
-- Dependencies: 235
-- Name: usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_id_seq', 1, true);


--
-- TOC entry 5122 (class 0 OID 0)
-- Dependencies: 237
-- Name: venta_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.venta_id_seq', 1, true);


--
-- TOC entry 4902 (class 2606 OID 16883)
-- Name: categoria categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categoria
    ADD CONSTRAINT categoria_pkey PRIMARY KEY (id);


--
-- TOC entry 4906 (class 2606 OID 16893)
-- Name: cliente cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cliente_pkey PRIMARY KEY (id);


--
-- TOC entry 4910 (class 2606 OID 16905)
-- Name: detalle_venta detalle_venta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_venta
    ADD CONSTRAINT detalle_venta_pkey PRIMARY KEY (id);


--
-- TOC entry 4912 (class 2606 OID 16913)
-- Name: marca marca_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.marca
    ADD CONSTRAINT marca_pkey PRIMARY KEY (id);


--
-- TOC entry 4916 (class 2606 OID 16925)
-- Name: movimiento_inventario movimiento_inventario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimiento_inventario
    ADD CONSTRAINT movimiento_inventario_pkey PRIMARY KEY (id);


--
-- TOC entry 4918 (class 2606 OID 16940)
-- Name: producto producto_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT producto_pkey PRIMARY KEY (id);


--
-- TOC entry 4920 (class 2606 OID 16950)
-- Name: proveedor proveedor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proveedor
    ADD CONSTRAINT proveedor_pkey PRIMARY KEY (id);


--
-- TOC entry 4922 (class 2606 OID 16958)
-- Name: rol rol_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT rol_pkey PRIMARY KEY (id);


--
-- TOC entry 4904 (class 2606 OID 16984)
-- Name: categoria uk35t4wyxqrevf09uwx9e9p6o75; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categoria
    ADD CONSTRAINT uk35t4wyxqrevf09uwx9e9p6o75 UNIQUE (nombre);


--
-- TOC entry 4924 (class 2606 OID 16990)
-- Name: rol uk43kr6s7bts1wqfv43f7jd87kp; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT uk43kr6s7bts1wqfv43f7jd87kp UNIQUE (nombre);


--
-- TOC entry 4926 (class 2606 OID 16992)
-- Name: usuario uk863n1y3x0jalatoir4325ehal; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uk863n1y3x0jalatoir4325ehal UNIQUE (username);


--
-- TOC entry 4908 (class 2606 OID 16986)
-- Name: cliente ukg18g15ijpoftfxm5v87awpbym; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT ukg18g15ijpoftfxm5v87awpbym UNIQUE (documento);


--
-- TOC entry 4914 (class 2606 OID 16988)
-- Name: marca ukg42kcgw83i65q054yikohi8b9; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.marca
    ADD CONSTRAINT ukg42kcgw83i65q054yikohi8b9 UNIQUE (nombre);


--
-- TOC entry 4928 (class 2606 OID 16971)
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


--
-- TOC entry 4930 (class 2606 OID 16982)
-- Name: venta venta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venta
    ADD CONSTRAINT venta_pkey PRIMARY KEY (id);


--
-- TOC entry 4935 (class 2606 OID 17018)
-- Name: producto fk868tnrt85f21kgcvt9bftgr8r; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT fk868tnrt85f21kgcvt9bftgr8r FOREIGN KEY (marca_id) REFERENCES public.marca(id);


--
-- TOC entry 4939 (class 2606 OID 17033)
-- Name: venta fka7yaj59nfh3gft0h38o5bv472; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venta
    ADD CONSTRAINT fka7yaj59nfh3gft0h38o5bv472 FOREIGN KEY (cliente_id) REFERENCES public.cliente(id);


--
-- TOC entry 4940 (class 2606 OID 17038)
-- Name: venta fkb28d98ltkhb0f8g3qypy8q2tl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venta
    ADD CONSTRAINT fkb28d98ltkhb0f8g3qypy8q2tl FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);


--
-- TOC entry 4933 (class 2606 OID 17003)
-- Name: movimiento_inventario fkd6bavqmj4o0mvn82ve46jac9v; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimiento_inventario
    ADD CONSTRAINT fkd6bavqmj4o0mvn82ve46jac9v FOREIGN KEY (producto_id) REFERENCES public.producto(id);


--
-- TOC entry 4931 (class 2606 OID 16998)
-- Name: detalle_venta fkhj0bf0515yg7equ11ab4xgq3f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_venta
    ADD CONSTRAINT fkhj0bf0515yg7equ11ab4xgq3f FOREIGN KEY (venta_id) REFERENCES public.venta(id);


--
-- TOC entry 4936 (class 2606 OID 17023)
-- Name: producto fkid8vjxky5juk3fnuc1sb9qarf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT fkid8vjxky5juk3fnuc1sb9qarf FOREIGN KEY (proveedor_id) REFERENCES public.proveedor(id);


--
-- TOC entry 4932 (class 2606 OID 16993)
-- Name: detalle_venta fkmi06vmeg5th7wdow1mxcqg78e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detalle_venta
    ADD CONSTRAINT fkmi06vmeg5th7wdow1mxcqg78e FOREIGN KEY (producto_id) REFERENCES public.producto(id);


--
-- TOC entry 4937 (class 2606 OID 17013)
-- Name: producto fkodqr7965ok9rwquj1utiamt0m; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.producto
    ADD CONSTRAINT fkodqr7965ok9rwquj1utiamt0m FOREIGN KEY (categoria_id) REFERENCES public.categoria(id);


--
-- TOC entry 4938 (class 2606 OID 17028)
-- Name: usuario fkshkwj12wg6vkm6iuwhvcfpct8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT fkshkwj12wg6vkm6iuwhvcfpct8 FOREIGN KEY (rol_id) REFERENCES public.rol(id);


--
-- TOC entry 4934 (class 2606 OID 17008)
-- Name: movimiento_inventario fkt6p6ejpbblav1phv0lgjpeg4r; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.movimiento_inventario
    ADD CONSTRAINT fkt6p6ejpbblav1phv0lgjpeg4r FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);


-- Completed on 2026-09-27 19:55:48

--
-- PostgreSQL database dump complete
--

\unrestrict xd0tBJrpOdnPFMGkBa2qGMim4ubActLYxBqkbap8veYHGhbaxDAyZlZ8RPzepCs

